### ISSUE TITLE
styla mat knapparna, fixa meny

### ISSUE THREAD

**Issue by Tejjsho** [Tejjsho/g63#1]
gör produkterna(dryckor, mat) ca hälften så breda
g̶ö̶r̶ ̶p̶r̶o̶d̶u̶k̶t̶e̶r̶n̶a̶(̶d̶r̶y̶c̶k̶o̶r̶,̶ ̶m̶a̶t̶)̶ ̶l̶i̶t̶e̶ ̶h̶ö̶g̶r̶e̶
eventuellt flytta knapparna på passande sätt

**Comment by Sprogis** [comment]
typ gört
